### ISSUE TITLE
Document is empty

### ISSUE THREAD

**Issue by jukylin** [aliyun/aliyun-mns-php-sdk#14]
你们，我们在线上使用阿里云消息发布订阅消息，偶尔会出现下面的报错，请问这是什么原因导致的
XMLReader::read():parser error : Document is empty

**Comment by zd-double** [comment]
可以再尝试下还有这个问题，还有问题把详细异常信息贴一下

**Comment by sydboys** [comment]
官方不解决一下这个问题么？
