### ISSUE TITLE
SubscriptionAttributes.php  composer更新问题

### ISSUE THREAD

**Issue by taroyutao** [aliyun/aliyun-mns-php-sdk#15]
SubscriptionAttributes.php 我看最新的更新是6月份，但是composer包的更新是4月份，这个用composer装不上最新的问题按呀，辛苦尽快更新一下composer。

**Comment by zd-double** [comment]
发布了1.1.0，请在更新下

{
  "require": {
     "aliyun/aliyun-mns-php-sdk": ">=1.1.0"
  }
}

**Comment by taroyutao** [comment]
ok，it's ok now.

Thanks for your great job.
![image](https://user-images.githubusercontent.com/20704268/62709503-0eb96500-ba28-11e9-8e08-3958c139d08b.png)
