### ISSUE TITLE
aliyun-mns-php-sdk/Samples/Queue/CreateQueueAndSendMessage.php 逻辑不完整 

### ISSUE THREAD

**Issue by alen19082062** [aliyun/aliyun-mns-php-sdk#16]
aliyun-mns-php-sdk/Samples/Queue/CreateQueueAndSendMessage.php
这个代码中， 这句
    $res = $queue->receiveMessage(30);
从对列中取消息，如果取到的消息为空，又如何处理呢， 能否把这个逻辑补上，告诉我们 $res 没取到消息会是什么样  

Java 的代码中，有以下的内容 
                Message popMsg = queue.popMessage();
                if (popMsg != null){ 
                }

**Comment by Pius-Z** [comment]
1. receiveMessage 方法获取到的消息为空，即队列中没有消息时，会抛出 MessageNotExistException 异常，进入异常处理流程。
2. receiveMessage 方法注释中有关于返回值和异常的详细说明。
