### ISSUE TITLE
composer.json中guzzlehttp/guzzle依赖应调整为版本6以内

### ISSUE THREAD

**Issue by artfantasy** [aliyun/aliyun-mns-php-sdk#17]
MNS SDK需要满足php version>=5.5.0条件的话，需要将composer.json中的guzzlehttp/guzzle调整为~6.0.0，而不能是>=6.0.0，因为guzzle最新版7必须要求PHP7.2+。
如果runtime的php版本是7.2以下，MNS SDK会报错。

**Comment by Pius-Z** [comment]
1. composer 会根据 PHP 版本下载符合要求的最高版本 guzzle。 
2. guzzle 7 异常体系变化导致的兼容性问题在 1.3.7 版本中已解决。

有其他问题，欢迎评论。
