### ISSUE TITLE
代码内处理异常响应的逻辑存在错误

### ISSUE THREAD

**Issue by ihipop** [aliyun/aliyun-mns-php-sdk#9]
如果遇到参数异常等错误，这个代码块里面引用了两个未定义变量。一个是 `$statusCode` 一个是 `$exception` 其他的文件内都存在类似错误 改下把你们。

https://github.com/aliyun/aliyun-mns-php-sdk/blob/2dbc92d187e1b1152079f418bc683c0443baddd4/AliyunMNS/Responses/BatchSendMessageResponse.php#L98-L114

**Comment by Pius-Z** [comment]
1.3.7 版本已修复。
